import {useEffect,useState} from "react";
import toast from "react-hot-toast";
import * as api from "@/controllers/me_controller";
import StatCard from "@/components/tracker/StatCard";
import {
  FaBullseye,
  FaCheckCircle,
  FaClipboardCheck,
  FaExclamationTriangle,
  FaFileAlt,
  FaMoneyBillWave,
  FaPaperclip,
  FaUserCheck,
  FaUsers,
} from "react-icons/fa";

// The M&E Dashboard tiles. One table so the figure, its icon and its tone
// stay together, and the grid is a plain map over the shared tracker card.
const NAVY = "text-[#0b2b5c]";
const pct = (value) => (value == null ? "—" : `${value}%`);

const OPERATION_TILES = [
  { label: "Participants", icon: <FaUsers />, tone: NAVY, value: (d) => d?.participants },
  { label: "Active participants", icon: <FaUserCheck />, tone: "text-emerald-600", value: (d) => d?.activeParticipants },
  { label: "Completion", icon: <FaBullseye />, tone: NAVY, value: (d) => pct(d?.completionRate) },
  { label: "Reports submitted", icon: <FaFileAlt />, tone: NAVY, value: (d) => d?.reportsSubmitted },
  { label: "Reports verified", icon: <FaCheckCircle />, tone: "text-emerald-600", value: (d) => d?.reportsVerified },
  { label: "Reports overdue", icon: <FaExclamationTriangle />, tone: "text-rose-600", value: (d) => d?.reportsOverdue },
  { label: "Baseline completion", icon: <FaClipboardCheck />, tone: NAVY, value: (d) => pct(d?.baselineCompletion) },
  { label: "Endline completion", icon: <FaClipboardCheck />, tone: NAVY, value: (d) => pct(d?.endlineCompletion) },
  { label: "Activities completed", icon: <FaCheckCircle />, tone: "text-emerald-600", value: (d) => d?.activitiesCompleted },
  { label: "Jobs created", icon: <FaUsers />, tone: NAVY, value: (d) => d?.jobsCreated },
  { label: "Capital mobilised", icon: <FaMoneyBillWave />, tone: "text-amber-500", value: (d) => Number(d?.capitalMobilised || 0).toLocaleString() },
  { label: "Open risks", icon: <FaExclamationTriangle />, tone: "text-rose-600", value: (d) => d?.openRisks },
  { label: "Evidence pending", icon: <FaPaperclip />, tone: "text-amber-500", value: (d) => d?.evidencePending },
  { label: "Data quality flags", icon: <FaExclamationTriangle />, tone: "text-amber-500", value: (d) => d?.openDataQualityFlags },
];
const U=r=>r?.body??r,C=({children})=><td className="px-4 py-3 text-sm">{children}</td>;
const T=({heads,rows,empty})=><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-50"><tr>{heads.map(h=><th key={h} className="px-4 py-3 text-sm font-semibold capitalize text-black">{h}</th>)}</tr></thead><tbody>{rows.length?rows:<tr><td colSpan={heads.length} className="p-10 text-center text-slate-500">{empty}</td></tr>}</tbody></table></div>;
function RecordEditor({programUuid,businessUuid,resource,onSaved}){const config={goals:[api.saveMeGoal,["title","target","unit","targetDate"]],funding:[api.saveMeFunding,["opportunityType","counterparty","amountRequested","currency","status"]],employment:[api.saveMeEmployment,["reportingPeriod","reportingDate","permanentMale","permanentFemale","temporaryMale","temporaryFemale","jobsCreated"]],impact:[api.saveMeImpact,["metricCode","metricName","category","unit","baselineValue","currentValue","reportingPeriod"]]}[resource], [v,setV]=useState({});if(!config)return null;const[saveFn,fields]=config,save=async()=>{if(!businessUuid)return toast.error("Enter a Business UUID first");const r=await saveFn(programUuid,{...v,businessUuid});r?.status===false?toast.error(r.message):(toast.success("Record saved"),setV({}),onSaved())};return <div className="mb-5 rounded-2xl border bg-white p-5"><h3 className="font-black">Add {resource} record</h3><div className="mt-3 grid gap-3 md:grid-cols-3">{fields.map(k=><input key={k} type={/Date$/.test(k)?"date":/amount|target|Value|Male|Female|jobs/i.test(k)?"number":"text"} placeholder={k.replace(/([A-Z])/g," $1")} value={v[k]||""} onChange={e=>setV({...v,[k]:e.target.value})} className="rounded-lg border px-3 py-2"/>)}</div><button onClick={save} className="mt-3 rounded-lg bg-[#16a34a] px-5 py-2 text-white">Save record</button></div>}
function ActivityEditor({programUuid,onSaved}){const[v,setV]=useState({name:"",activityType:"training",activityDate:"",location:"",facilitator:"",plannedParticipants:""});const save=async()=>{if(!v.name||!v.activityDate)return toast.error("Activity name and date are required");const r=await api.saveMeActivity(programUuid,v);r?.status===false?toast.error(r.message):(toast.success("Activity saved"),setV({...v,name:"",activityDate:""}),onSaved())};return <div className="mb-5 rounded-2xl border bg-white p-5"><h3 className="font-black">Add programme activity</h3><div className="mt-3 grid gap-3 md:grid-cols-3">{Object.keys(v).map(k=><input key={k} type={k==="activityDate"?"date":k==="plannedParticipants"?"number":"text"} placeholder={k.replace(/([A-Z])/g," $1")} value={v[k]} onChange={e=>setV({...v,[k]:e.target.value})} className="rounded-lg border px-3 py-2"/>)}</div><button onClick={save} className="mt-3 rounded-lg bg-[#16a34a] px-5 py-2 text-white">Save activity</button></div>}
function TemplateEditor({programUuid,onSaved}){const[v,setV]=useState({name:"",assessmentType:"baseline",scoringScale:5,question:"",area:"Business Strategy"});const save=async()=>{if(!v.name||!v.question)return toast.error("Template name and question are required");const r=await api.saveMeAssessmentTemplate(programUuid,{name:v.name,assessmentType:v.assessmentType,scoringScale:v.scoringScale,questions:[{question:v.question,area:v.area,responseType:"scale"}]});r?.status===false?toast.error(r.message):(toast.success("Assessment template saved"),setV({...v,name:"",question:""}),onSaved())};return <div className="mb-5 rounded-2xl border bg-white p-5"><h3 className="font-black">Create assessment template</h3><div className="mt-3 grid gap-3 md:grid-cols-3"><input placeholder="Template name" value={v.name} onChange={e=>setV({...v,name:e.target.value})} className="rounded-lg border px-3 py-2"/><select value={v.assessmentType} onChange={e=>setV({...v,assessmentType:e.target.value})} className="rounded-lg border px-3 py-2">{["baseline","midline","endline","custom"].map(x=><option key={x}>{x}</option>)}</select><input type="number" min="2" max="10" value={v.scoringScale} onChange={e=>setV({...v,scoringScale:e.target.value})} className="rounded-lg border px-3 py-2"/><input placeholder="Capability area" value={v.area} onChange={e=>setV({...v,area:e.target.value})} className="rounded-lg border px-3 py-2"/><input placeholder="Assessment question" value={v.question} onChange={e=>setV({...v,question:e.target.value})} className="rounded-lg border px-3 py-2 md:col-span-2"/></div><button onClick={save} className="mt-3 rounded-lg bg-[#16a34a] px-5 py-2 text-white">Save template</button></div>}
export default function ProgramMEOperations({programUuid,section,canManage}){const[data,setData]=useState(null),[loading,setLoading]=useState(true),[businessUuid,setBusinessUuid]=useState(()=>new URLSearchParams(window.location.search).get("businessUuid")||"");const load=async()=>{setLoading(true);const p=businessUuid?{businessUuid}:{},f={operations:()=>api.getMeOperationsDashboard(programUuid),reports:()=>api.getMeReports(programUuid,p),assessments:()=>businessUuid?api.compareMeAssessments(programUuid,p):api.getMeAssessments(programUuid,p),assessmentSetup:()=>api.getMeAssessmentTemplates(programUuid),performance:()=>api.getMeMetrics(programUuid,p),evidence:()=>api.getMeEvidence(programUuid,p),activities:()=>api.getMeActivities(programUuid),goals:()=>api.getMeGoals(programUuid,p),funding:()=>api.getMeFunding(programUuid,p),employment:()=>api.getMeEmployment(programUuid,p),impact:()=>api.getMeImpact(programUuid,p),risks:()=>api.getMeRisks(programUuid,p),mentorship:()=>api.getMeMentorship(programUuid,p),quality:()=>api.getMeDataQuality(programUuid,p)};const r=await f[section]?.();if(r?.status===false)toast.error(r.message);setData(U(r));setLoading(false)};useEffect(()=>{load()},[programUuid,section]);if(loading)return <div className="rounded-2xl border bg-white p-12 text-center">Loading M&amp;E records...</div>;
if(section==="operations"){const run=async(fn,label)=>{const r=await fn(programUuid);r?.status===false?toast.error(r.message):(toast.success(label),load())};return <div className="space-y-4">{canManage&&<div className="flex gap-3"><button onClick={()=>run(api.refreshMeRisks,"Risk flags refreshed")} className="rounded-lg bg-amber-600 px-4 py-2 text-white">Refresh risk flags</button><button onClick={()=>run(api.generateMeReminders,"Reminders generated")} className="rounded-lg bg-[#082d77] px-4 py-2 text-white">Generate reminders</button></div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{OPERATION_TILES.map((tile)=><StatCard key={tile.label} label={tile.label} value={tile.value(data) ?? 0} icon={tile.icon} tone={tile.tone}/>)}</div></div>};const filter=<div className="mb-5 flex max-w-xl gap-2"><input value={businessUuid} onChange={e=>setBusinessUuid(e.target.value)} placeholder="Business UUID for drill-down" className="flex-1 rounded-lg border px-3 py-2"/><button onClick={load} className="rounded-lg bg-[#082d77] px-4 text-white">Apply</button></div>,rows=Array.isArray(data)?data:data?.data||[];
const specs={activities:[["Activity","Type","Date","Participants","Attendance","Completion","Satisfaction","Knowledge gain","Status"],r=>[r.name,r.activityType,String(r.activityDate||"").slice(0,10),r.actualParticipants??r.attendance?.length??0,r.attendanceRate==null?"—":`${r.attendanceRate}%`,r.completionRate==null?"—":`${r.completionRate}%`,r.averageSatisfaction??"—",r.knowledgeImprovement??"—",r.status]],goals:[["Goal","Target","Due date","Progress","Status"],r=>[r.title,`${r.target??"—"} ${r.unit||""}`,r.targetDate||"—",`${r.progressPercentage||0}%`,r.status]],funding:[["Opportunity","Counterparty","Requested","Received","Status"],r=>[r.opportunityType,r.counterparty||"—",`${r.currency} ${Number(r.amountRequested||0).toLocaleString()}`,`${r.currency} ${Number(r.amountReceived||0).toLocaleString()}`,r.status]],employment:[["Period","Permanent","Temporary","Jobs created","Verification"],r=>[r.reportingPeriod,Number(r.permanentMale||0)+Number(r.permanentFemale||0),Number(r.temporaryMale||0)+Number(r.temporaryFemale||0),r.jobsCreated,r.verificationStatus]],impact:[["Metric","Category","Baseline","Current","Period","Verification"],r=>[r.metricName,r.category,r.baselineValue??"—",`${r.currentValue} ${r.unit}`,r.reportingPeriod,r.verificationStatus]],risks:[["Business","Level","Reasons","Detected","Status","Intervention"],r=>[r.businessId,r.riskLevel,Array.isArray(r.reasons)?r.reasons.join(", "):JSON.stringify(r.reasons),String(r.detectedAt||"").slice(0,10),r.status,r.intervention||"—"]],performance:[["Metric","Date","Value","Unit","Verification"],r=>[r.metricCode,r.reportingDate,r.numericValue??r.textValue??"—",r.unit||"—",r.verificationStatus]]};if(specs[section]){const[h,v]=specs[section];return <>{section==="activities"&&canManage&&<ActivityEditor programUuid={programUuid} onSaved={load}/>} {canManage&&["goals","funding","employment","impact"].includes(section)&&<RecordEditor programUuid={programUuid} businessUuid={businessUuid} resource={section} onSaved={load}/>} {section!=="activities"&&filter}<T heads={h} empty={`No ${section} records found.`} rows={rows.map(r=><tr key={r.uuid} className="border-t">{v(r).map((x,i)=><C key={i}>{x}</C>)}</tr>)}/></>}
if(section==="reports"){const review=async(r,status)=>{const x=await api.reviewMeReport(programUuid,r.uuid,{status});x?.status===false?toast.error(x.message):(toast.success(`Report ${status}`),load())},download=async()=>{try{const x=await api.downloadMeExport(programUuid,"reports"),url=URL.createObjectURL(x.data),a=document.createElement("a");a.href=url;a.download="me-progress-reports.csv";a.click();URL.revokeObjectURL(url)}catch{toast.error("Export failed")}};return <><div className="flex items-start justify-between gap-3">{filter}{canManage&&<button onClick={download} className="rounded-lg bg-[#082d77] px-4 py-2 text-white">Export CSV</button>}</div><T heads={["Period","Business","Revenue","Jobs","Status","Action"]} empty="No reports found." rows={rows.map(r=><tr key={r.uuid} className="border-t"><C>{r.reportingPeriod}</C><C>{r.businessId}</C><C>{Number(r.revenue||0).toLocaleString()}</C><C>{r.jobsCreated??"—"}</C><C>{r.status}</C><C>{canManage&&r.status==="submitted"&&<span className="flex gap-2"><button onClick={()=>review(r,"verified")} className="text-emerald-700">Verify</button><button onClick={()=>review(r,"rejected")} className="text-rose-700">Reject</button></span>}</C></tr>)}/></>};if(section==="assessments"){if(data?.changes)return <>{filter}<T heads={["Metric","Baseline","Current","Change","% change"]} empty="No verified comparison available." rows={[...(data.changes||[]),...(data.capabilityChanges||[]).map(x=>({...x,metric:`Capability: ${x.metric}`}))].map(r=><tr key={r.metric} className="border-t">{[r.metric,r.baseline,r.current,r.absoluteChange,r.percentageChange==null?"—":`${r.percentageChange}%`].map((x,i)=><C key={i}>{x}</C>)}</tr>)}/></>;const review=async(r,status)=>{const x=await api.reviewMeAssessment(programUuid,r.uuid,{status});x?.status===false?toast.error(x.message):(toast.success(`Assessment ${status}`),load())};return <>{filter}<T heads={["Type","Date","Business","Status","Action"]} empty="No assessments found." rows={rows.map(r=><tr key={r.uuid} className="border-t">{[r.assessmentType,r.assessmentDate,r.businessId,r.status].map((x,i)=><C key={i}>{x}</C>)}<C>{canManage&&["submitted","under_review"].includes(r.status)&&<span className="flex gap-2"><button onClick={()=>review(r,"verified")} className="text-emerald-700">Verify</button><button onClick={()=>review(r,"rejected")} className="text-rose-700">Reject</button></span>}</C></tr>)}/></>}
if(section==="mentorship"){const sessions=data?.data||[],cards=[["Sessions",data?.totalSessions],["Hours",data?.mentorshipHours],["Entrepreneurs mentored",data?.entrepreneursMentored],["Action completion",data?.actionCompletionRate==null?"—":`${data.actionCompletionRate}%`],["Overdue actions",data?.overdueActions]];return <>{filter}<div className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([l,v])=><div key={l} className="rounded-xl border bg-white p-4"><b className="text-2xl text-[#082d77]">{v??0}</b><p className="text-sm text-slate-500">{l}</p></div>)}</div><T heads={["Date","Topic","Duration","Action","Deadline","Status"]} empty="No mentorship sessions." rows={sessions.map(r=><tr key={r.uuid} className="border-t">{[r.sessionDate,r.topic||"—",r.durationMinutes?`${r.durationMinutes} min`:"—",r.actionsAgreed||"—",r.actionDeadline||"—",r.actionStatus].map((x,i)=><C key={i}>{x}</C>)}</tr>)}/></>}
if(section==="assessmentSetup")return <>{canManage&&<TemplateEditor programUuid={programUuid} onSaved={load}/>}<T heads={["Template","Type","Scale","Questions","Status"]} empty="No assessment templates." rows={rows.map(r=><tr key={r.uuid} className="border-t">{[r.name,r.assessmentType,`1–${r.scoringScale}`,r.questions?.length||0,r.active?"Active":"Inactive"].map((x,i)=><C key={i}>{x}</C>)}</tr>)}/></>;
if(section==="quality")return <>{filter}<T heads={["Rule","Severity","Message","Business","Detected","Status"]} empty="No data-quality flags." rows={rows.map(r=><tr key={r.uuid} className="border-t">{[r.ruleCode,r.severity,r.message,r.businessId||"—",String(r.detectedAt||"").slice(0,10),r.status].map((x,i)=><C key={i}>{x}</C>)}</tr>)}/></>;
const verify=async(r,status)=>{const x=await api.reviewMeEvidence(programUuid,r.uuid,{status});x?.status===false?toast.error(x.message):(toast.success(`Evidence ${status}`),load())},open=async r=>{if(!r.storageKey)return window.open(r.fileUrl,"_blank","noopener");try{const x=await api.downloadMeEvidence(programUuid,r.uuid),url=URL.createObjectURL(x.data);window.open(url,"_blank","noopener");setTimeout(()=>URL.revokeObjectURL(url),30000)}catch{toast.error("Unable to open evidence")}};return <>{filter}<T heads={["Type","Record","Description","Verification","File","Action"]} empty="No evidence found." rows={rows.map(r=><tr key={r.uuid} className="border-t"><C>{r.evidenceType}</C><C>{r.entityType}</C><C>{r.description||"—"}</C><C>{r.verificationStatus}</C><C><button onClick={()=>open(r)} className="text-[#082d77]">Open</button></C><C>{canManage&&r.verificationStatus==="pending"&&<span className="flex gap-2"><button onClick={()=>verify(r,"verified")} className="text-emerald-700">Verify</button><button onClick={()=>verify(r,"rejected")} className="text-rose-700">Reject</button></span>}</C></tr>)}/></>}
